In [1]:
import numpy as np

In [42]:
y = np.zeros((4,3))
y_hat = np.zeros((4,3))

In [48]:
y_hat[0,1]=1
y[0,1]=1
y_hat[1,0]=1
y[1,1]=1
y_hat[2,0]=1
y[2,1]=1
y_hat[3,1]=1
y[3,1]=1

In [49]:
print(y)
print(y_hat)

[[ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]]
[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]


In [50]:
err = y-y_hat

In [51]:
sum(sum(abs(err)))/2

2.0

4